### ISSUE TITLE
Increase touch area of tooltip items

### ISSUE THREAD

**Issue by jrauh** [samaritanministries/dashing#48]
When trying to touch-hover a tooltip, it will often highlight the text next to it, rather than highlighting the tooltip.

![img_f9df0bb7277f-1](https://user-images.githubusercontent.com/7129122/37772171-d2c6f840-2da7-11e8-8f2f-868be6d8119c.jpeg)

Consider increasing the icon size, and making the adjacent text not highlightable.

**Comment by jrauh** [comment]
On mobile, we should consider giving the tooltip text a **dotted underline**. This seems to be an emerging design pattern. 

We should also consider making the tooltip appear on **tap**, not touch-start/touch-leave.

- https://uxplanet.org/tooltips-in-ui-design-f63e117aa3d1
- https://foundation.zurb.com/sites/docs/v/5.5.3/components/tooltips.html

**Comment by jrauh** [comment]
Here's one option. Treat the icon like a button-icon to give it more padding.

![image](https://user-images.githubusercontent.com/7129122/38621679-f9d97754-3d66-11e8-8641-f71c1548b455.png)

**Comment by aknobloch3** [comment]
And the increased padding would just happen on mobile? I kind of like that idea. Seems like Google Material has that sort of extra padding.
<img width="796" alt="screen shot 2018-04-11 at 9 31 40 am" src="https://user-images.githubusercontent.com/26393016/38623453-5250719a-3d6b-11e8-8d0e-1b61441d7459.png">
